[package]
name = "tangle-me"
version = "0.1.0"
authors = ["/alex/ <Al3k5@protonmail.com>"]
edition = "2018"

[dependencies]
trinary = { git = "https://github.com/Alex6323/trinary.git" }
trits-module-preview = { git = "https://github.com/Alex6323/trits-module-preview.git" }
