[package]
name = "tangle"
version = "0.1.0"
authors = ["/alex/ <Al3k5@protonmail.com>"]
edition = "2018"

[dependencies]
indexmap = "1.3.2"
smallvec = "1.3.0"

bee-bundle = { git = "https://github.com/Alex6323/bee-p.git" }